package com.bzapata.triangle.deltaCoreKt.inputs

enum class StandardGameController {
    MENU,
    UP, DOWN, LEFT, RIGHT,
    LEFT_THUMBSTICK_UP, LEFT_THUMBSTICK_DOWN, LEFT_THUMBSTICK_LEFT, LEFT_THUMBSTICK_RIGHT,
    RIGHT_THUMBSTICK_UP,RIGHT_THUMBSTICK_DOWN, RIGHT_THUMBSTICK_LEFT, RIGHT_THUMBSTICK_RIGHT,
    A,B,X,Y,
    START, SELECT,
    L1,L2,L3,
    R1,R2,R3,
}